import { describe, expect, it } from 'vitest'
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'

// public/third-party-licenses.txt is generated by `npm run build` (scripts/third-party-licenses.mjs)
const file = join(__dirname, '..', 'public', 'third-party-licenses.txt')

describe.runIf(existsSync(file))('third-party licenses', () => {
  const text = existsSync(file) ? readFileSync(file, 'utf8') : ''
  const headers = text.split(/\n={78}\n/).filter((_, i) => i % 2 === 1)

  it('lists the bundled npm packages, the Rust crates and the Unicode data', () => {
    const all = headers.join(', ')
    for (const name of ['prosemirror-model', 'unified', 'micromark', 'highlight.js', 'temml', '@tauri-apps/api']) expect(all).toContain(name + ' ')
    for (const crate of ['tauri', 'serde', 'ureq']) expect(all).toMatch(new RegExp(`(^|, )${crate} [\\d.]+ \\(Rust\\)`))
    expect(all).toContain('Unicode Character Database')
  })

  it('leaves out development tools', () => {
    for (const dev of ['vitest', 'vite', 'typescript', '@tauri-apps/cli']) expect(headers.join(', ')).not.toMatch(new RegExp(`(^|, )${dev.replace(/[./]/g, '\\$&')} \\d`))
  })

  it('has the Apache License text once', () => {
    expect(text.split('TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION').length - 1).toBeLessThanOrEqual(2)
    expect(text).toContain('Apache License 2.0 – full text: see')
  })

  it('stays small', () => {
    expect(text.length).toBeLessThan(600 * 1024)
  })
})
